### ISSUE TITLE
White font color - makes diff unreadable when Chrome is switched to dark mode

### ISSUE THREAD

**Issue by klonos** [daviddengcn/patch-ext#14] opened 2022-06-22 18:54 UTC
This is what I am seeing lately (I imagine after a recent Chrome update - currently running `Version 102.0.5005.61 (Official Build) (x86_64)`):

![image](https://user-images.githubusercontent.com/2423362/175114662-c7020dc2-582f-4f29-8632-c13cb16ae5fd.png)

**Comment by daviddengcn** [comment] 2022-06-22 20:30
Thanks for reporting this. I'll take a look. I guess some fixes on css/js are needed. It'll be nice if anyone can directly provide the fixes.

**Comment by wilfred-s** [comment] 2022-08-04 05:11
The issue is not with the chrome update. When you have dark mode enabled the background stays white but the font colour get changed from dark to light automatically. That causes the test to disappear into the white background. Turning off dark mode renders the diff perfectly fine even on the latest chrome releases.

Toggling the render preference in the development tools and setting `prefers-color-scheme: light` changes it for just the page back to a readable view without needing to change the whole browser back to light mode.

Wrapping the background setting in:
```
@media (prefers-color-scheme: dark) {
...
}
@media (prefers-color-scheme: light) {
...
}
```

**Comment by danish-ti** [comment] 2024-10-28 11:20
Has there been any fix for this? I am trying this and I still see this issue with Light / Dark mode. The issue is still seen even after disabling dark mode in chrome. The only workaround I have is to change <meta name="color-scheme" content="light dark"> to <meta name="color-scheme" content="light">.
However this change gets lost during refresh. Has anyone found any permanent fix for his?

**Comment by daviddengcn** [comment] 2024-12-21 06:41
I've just submitted a change fixing the light-dark color issue. But I need to do another change to use new manifest version for chrome extension release.

**Comment by daviddengcn** [comment] 2024-12-23 05:05
1.9 will be friendly to dark model. Please file new bugs if any other problems found.

**Closed as completed by daviddengcn** 2024-12-23 05:05 UTC

**Comment by danish-ti** [comment] 2024-12-30 05:56
@daviddengcn  Just tested version 1.9 chrome extension and I can confirm that the patch viewer is fixed for dark mode. Thanks for the fix.
